package com.mxxk.lightstar.entity;

import javax.persistence.*;

@Entity
@Table(name="shares")
public class Shares {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.id
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.ent_name
     *
     * @mbggenerated
     */
    @Column(name="ent_name")
    private String entName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.english_name
     *
     * @mbggenerated
     */
    @Column(name="english_name")
    private String englishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.stock_name
     *
     * @mbggenerated
     */
    @Column(name="stock_name")
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.stock_code
     *
     * @mbggenerated
     */
    @Column(name="stock_code")
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.used_name
     *
     * @mbggenerated
     */
    @Column(name="used_name")
    private String usedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.stock_type
     *
     * @mbggenerated
     */
    @Column(name="stock_type")
    private String stockType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.list_date
     *
     * @mbggenerated
     */
    @Column(name="list_date")
    private String listDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.industry
     *
     * @mbggenerated
     */
    @Column(name="industry")
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.registed_capital
     *
     * @mbggenerated
     */
    @Column(name="registered_capital")
    private String registeredCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.tradable_shares
     *
     * @mbggenerated
     */
    @Column(name="tradable_shares")
    private String tradableShares;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.business_scope
     *
     * @mbggenerated
     */
    @Column(name="business_scope")
    private String businessScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.main_business
     *
     * @mbggenerated
     */
    @Column(name="main_business")
    private String mainBusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.ent_background
     *
     * @mbggenerated
     */
    @Column(name="ent_background")
    private String entBackground;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.bonus_result
     *
     * @mbggenerated
     */
    @Column(name="bonus_result")
    private String bonusResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.hold_share
     *
     * @mbggenerated
     */
    @Column(name="hold_share")
    private String holdShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.profit
     *
     * @mbggenerated
     */
    @Column(name="profit")
    private String profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.share_bonus
     *
     * @mbggenerated
     */
    @Column(name="share_bonus")
    private String shareBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.stock_info
     *
     * @mbggenerated
     */
    @Column(name="stock_info")
    private String stockInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.id
     *
     * @return the value of shares.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.id
     *
     * @param id the value for shares.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.ent_name
     *
     * @return the value of shares.ent_name
     *
     * @mbggenerated
     */
    public String getEntName() {
        return entName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.ent_name
     *
     * @param entName the value for shares.ent_name
     *
     * @mbggenerated
     */
    public void setEntName(String entName) {
        this.entName = entName == null ? null : entName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.english_name
     *
     * @return the value of shares.english_name
     *
     * @mbggenerated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.english_name
     *
     * @param englishName the value for shares.english_name
     *
     * @mbggenerated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.stock_name
     *
     * @return the value of shares.stock_name
     *
     * @mbggenerated
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.stock_name
     *
     * @param stockName the value for shares.stock_name
     *
     * @mbggenerated
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.stock_code
     *
     * @return the value of shares.stock_code
     *
     * @mbggenerated
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.stock_code
     *
     * @param stockCode the value for shares.stock_code
     *
     * @mbggenerated
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.used_name
     *
     * @return the value of shares.used_name
     *
     * @mbggenerated
     */
    public String getUsedName() {
        return usedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.used_name
     *
     * @param usedName the value for shares.used_name
     *
     * @mbggenerated
     */
    public void setUsedName(String usedName) {
        this.usedName = usedName == null ? null : usedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.stock_type
     *
     * @return the value of shares.stock_type
     *
     * @mbggenerated
     */
    public String getStockType() {
        return stockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.stock_type
     *
     * @param stockType the value for shares.stock_type
     *
     * @mbggenerated
     */
    public void setStockType(String stockType) {
        this.stockType = stockType == null ? null : stockType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.list_date
     *
     * @return the value of shares.list_date
     *
     * @mbggenerated
     */
    public String getListDate() {
        return listDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.list_date
     *
     * @param listDate the value for shares.list_date
     *
     * @mbggenerated
     */
    public void setListDate(String listDate) {
        this.listDate = listDate == null ? null : listDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.industry
     *
     * @return the value of shares.industry
     *
     * @mbggenerated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.industry
     *
     * @param industry the value for shares.industry
     *
     * @mbggenerated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.registed_capital
     *
     * @return the value of shares.registed_capital
     *
     * @mbggenerated
     */
    public String getRegisteredCapital() {
        return registeredCapital;
    }

    public void setRegisteredCapital(String registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.tradable_shares
     *
     * @return the value of shares.tradable_shares
     *
     * @mbggenerated
     */
    public String getTradableShares() {
        return tradableShares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.tradable_shares
     *
     *   tradableShares the value for shares.tradable_shares
     *
     * @mbggenerated
     */
    public void setTradableShares(String tradableShares) {
        this.tradableShares = tradableShares == null ? null : tradableShares.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.business_scope
     *
     * @return the value of shares.business_scope
     *
     * @mbggenerated
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.business_scope
     *
     * @param businessScope the value for shares.business_scope
     *
     * @mbggenerated
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.main_business
     *
     * @return the value of shares.main_business
     *
     * @mbggenerated
     */
    public String getMainBusiness() {
        return mainBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.main_business
     *
     * @param mainBusiness the value for shares.main_business
     *
     * @mbggenerated
     */
    public void setMainBusiness(String mainBusiness) {
        this.mainBusiness = mainBusiness == null ? null : mainBusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.ent_background
     *
     * @return the value of shares.ent_background
     *
     * @mbggenerated
     */
    public String getEntBackground() {
        return entBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.ent_background
     *
     * @param entBackground the value for shares.ent_background
     *
     * @mbggenerated
     */
    public void setEntBackground(String entBackground) {
        this.entBackground = entBackground == null ? null : entBackground.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.bonus_result
     *
     * @return the value of shares.bonus_result
     *
     * @mbggenerated
     */
    public String getBonusResult() {
        return bonusResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.bonus_result
     *
     * @param bonusResult the value for shares.bonus_result
     *
     * @mbggenerated
     */
    public void setBonusResult(String bonusResult) {
        this.bonusResult = bonusResult == null ? null : bonusResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.hold_share
     *
     * @return the value of shares.hold_share
     *
     * @mbggenerated
     */
    public String getHoldShare() {
        return holdShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.hold_share
     *
     * @param holdShare the value for shares.hold_share
     *
     * @mbggenerated
     */
    public void setHoldShare(String holdShare) {
        this.holdShare = holdShare == null ? null : holdShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.profit
     *
     * @return the value of shares.profit
     *
     * @mbggenerated
     */
    public String getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.profit
     *
     * @param profit the value for shares.profit
     *
     * @mbggenerated
     */
    public void setProfit(String profit) {
        this.profit = profit == null ? null : profit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.share_bonus
     *
     * @return the value of shares.share_bonus
     *
     * @mbggenerated
     */
    public String getShareBonus() {
        return shareBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.share_bonus
     *
     * @param shareBonus the value for shares.share_bonus
     *
     * @mbggenerated
     */
    public void setShareBonus(String shareBonus) {
        this.shareBonus = shareBonus == null ? null : shareBonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.stock_info
     *
     * @return the value of shares.stock_info
     *
     * @mbggenerated
     */
    public String getStockInfo() {
        return stockInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.stock_info
     *
     * @param stockInfo the value for shares.stock_info
     *
     * @mbggenerated
     */
    public void setStockInfo(String stockInfo) {
        this.stockInfo = stockInfo == null ? null : stockInfo.trim();
    }
}